// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: rbPHTCCgxa1NtQh9SvuYvu
// Component: MymVTz9DK7ENL1
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { ProductBox } from "@plasmicpkgs/commerce"; // plasmic-import: 1gYJf_XBZUAD/codeComponent
import { ProductTextField } from "@plasmicpkgs/commerce"; // plasmic-import: S1F4q0wN6b/codeComponent
import { ProductPriceComponent } from "@plasmicpkgs/commerce"; // plasmic-import: _PaJxGc8gf/codeComponent
import LinkButton from "../../LinkButton"; // plasmic-import: dlrqhj701dimA/component
import { ProductMedia } from "@plasmicpkgs/commerce"; // plasmic-import: qpULM0wwWW/codeComponent
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_library_plasmic_color_type_css from "../library_plasmic_color_type/plasmic_library_plasmic_color_type.module.css"; // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss
import projectcss from "./plasmic_furn_e_commerce.module.css"; // plasmic-import: rbPHTCCgxa1NtQh9SvuYvu/projectcss
import sty from "./PlasmicProductCarousel.module.css"; // plasmic-import: MymVTz9DK7ENL1/css
import DotCircleOIcon from "./icons/PlasmicIcon__DotCircleO"; // plasmic-import: XIL4VrvZvzt5Zr/icon
import CircleOIcon from "./icons/PlasmicIcon__CircleO"; // plasmic-import: psKycC_3DEhQW-/icon

export const PlasmicProductCarousel__VariantProps = new Array("slider");

export const PlasmicProductCarousel__ArgProps = new Array();

function PlasmicProductCarousel__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = args;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_library_plasmic_color_type_css.plasmic_tokens,
        sty.root
      )}
    >
      <ProductBox
        data-plasmic-name={"productBox"}
        data-plasmic-override={overrides.productBox}
        className={classNames("__wab_instance", sty.productBox, {
          [sty.productBoxslider_second]: hasVariant(
            variants,
            "slider",
            "second"
          ),

          [sty.productBoxslider_third]: hasVariant(variants, "slider", "third")
        })}
        id={
          hasVariant(variants, "slider", "third")
            ? "valvet-accent-arm-chair"
            : hasVariant(variants, "slider", "second")
            ? "mapple-wood-accent-chair"
            : "cloth-covered-accent-chair"
        }
      >
        <ph.DataCtxReader>
          {$ctx => (
            <>
              <div className={classNames(projectcss.all, sty.freeBox__wBou4)}>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__vJ6Mh, {
                    [sty.freeBoxslider_first__vJ6MhwTw7E]: hasVariant(
                      variants,
                      "slider",
                      "first"
                    ),

                    [sty.freeBoxslider_second__vJ6MhBWtBk]: hasVariant(
                      variants,
                      "slider",
                      "second"
                    ),

                    [sty.freeBoxslider_third__vJ6MhhHdbL]: hasVariant(
                      variants,
                      "slider",
                      "third"
                    )
                  })}
                >
                  <div
                    data-plasmic-name={"text"}
                    data-plasmic-override={overrides.text}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text
                    )}
                  >
                    {"Great Design Collection"}
                  </div>

                  <ProductTextField
                    className={classNames(
                      "__wab_instance",
                      sty.productTextField__jiZ1J
                    )}
                    field={"name"}
                  />

                  <ProductTextField
                    className={classNames(
                      "__wab_instance",
                      sty.productTextField__wQrEg
                    )}
                    field={"description"}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox__flzV)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__qhZrL)}
                    />

                    <ProductPriceComponent
                      data-plasmic-name={"productPrice"}
                      data-plasmic-override={overrides.productPrice}
                      className={classNames("__wab_instance", sty.productPrice)}
                    />
                  </div>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox___4S8B9)}
                  >
                    <LinkButton
                      className={classNames(
                        "__wab_instance",
                        sty.linkButton__v0D0L
                      )}
                      text={"⊕ Add to cart"}
                      type={"solidOrange"}
                    />

                    <LinkButton
                      className={classNames(
                        "__wab_instance",
                        sty.linkButton__iisGl
                      )}
                      text={"More Info"}
                      type={"blankOrange"}
                    />
                  </p.Stack>
                </p.Stack>

                <div className={classNames(projectcss.all, sty.freeBox__nx64W)}>
                  <ProductMedia
                    data-plasmic-name={"productMedia"}
                    data-plasmic-override={overrides.productMedia}
                    className={classNames("__wab_instance", sty.productMedia, {
                      [sty.productMediaslider_second]: hasVariant(
                        variants,
                        "slider",
                        "second"
                      )
                    })}
                  />
                </div>
              </div>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__jlOup)}
              >
                <p.PlasmicIcon
                  PlasmicIconType={
                    hasVariant(variants, "slider", "third")
                      ? CircleOIcon
                      : hasVariant(variants, "slider", "second")
                      ? CircleOIcon
                      : DotCircleOIcon
                  }
                  className={classNames(projectcss.all, sty.svg__cfDhA, {
                    [sty.svgslider_second__cfDhAbWtBk]: hasVariant(
                      variants,
                      "slider",
                      "second"
                    ),

                    [sty.svgslider_third__cfDhAhHdbL]: hasVariant(
                      variants,
                      "slider",
                      "third"
                    )
                  })}
                  role={"img"}
                />

                <p.PlasmicIcon
                  PlasmicIconType={
                    hasVariant(variants, "slider", "second")
                      ? DotCircleOIcon
                      : CircleOIcon
                  }
                  className={classNames(projectcss.all, sty.svg__fsCqJ, {
                    [sty.svgslider_first__fsCqJwTw7E]: hasVariant(
                      variants,
                      "slider",
                      "first"
                    ),

                    [sty.svgslider_second__fsCqJbWtBk]: hasVariant(
                      variants,
                      "slider",
                      "second"
                    ),

                    [sty.svgslider_third__fsCqJhHdbL]: hasVariant(
                      variants,
                      "slider",
                      "third"
                    )
                  })}
                  role={"img"}
                />

                <p.PlasmicIcon
                  PlasmicIconType={
                    hasVariant(variants, "slider", "third")
                      ? DotCircleOIcon
                      : CircleOIcon
                  }
                  className={classNames(projectcss.all, sty.svg__rD2J5, {
                    [sty.svgslider_third__rD2J5HHdbL]: hasVariant(
                      variants,
                      "slider",
                      "third"
                    )
                  })}
                  role={"img"}
                />
              </p.Stack>
            </>
          )}
        </ph.DataCtxReader>
      </ProductBox>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "productBox", "text", "productPrice", "productMedia"],
  productBox: ["productBox", "text", "productPrice", "productMedia"],
  text: ["text"],
  productPrice: ["productPrice"],
  productMedia: ["productMedia"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicProductCarousel__ArgProps,
          internalVariantPropNames: PlasmicProductCarousel__VariantProps
        }),

      [props, nodeName]
    );

    return PlasmicProductCarousel__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicProductCarousel";
  } else {
    func.displayName = `PlasmicProductCarousel.${nodeName}`;
  }
  return func;
}

export const PlasmicProductCarousel = Object.assign(
  // Top-level PlasmicProductCarousel renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    productBox: makeNodeComponent("productBox"),
    text: makeNodeComponent("text"),
    productPrice: makeNodeComponent("productPrice"),
    productMedia: makeNodeComponent("productMedia"),
    // Metadata about props expected for PlasmicProductCarousel
    internalVariantProps: PlasmicProductCarousel__VariantProps,
    internalArgProps: PlasmicProductCarousel__ArgProps
  }
);

export default PlasmicProductCarousel;
/* prettier-ignore-end */
